name: My GitHub workflow
on:
  push:

jobs:
  npm-node-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: print node version
        run: node --version

      - name: print npm version
        run: npm --version

      - name: install dependencies
        run: npm ci
